#!/bin/bash
function asdf_latest() {
    asdf plugin add $1
    asdf install $1 latest
    asdf global $1 latest
}

echo "Installing golang latest version"
asdf_latest golang

echo "Installing JAVA"
asdf plugin add java
asdf install java openjdk-11.0.2
asdf install java openjdk-19.0.1
asdf global java openjdk-11.0.2

echo "Installing NodeJS"
asdf plugin add nodejs
asdf install nodejs lts
asdf global nodejs lts

asdf_latest yarn

echo "Installing Clojure"
asdf plugin add clj https://github.com/yuhribernardes/asdf-clojure.git
asdf install clj latest
asdf global clj latest

asdf_latest leiningen

yay -S --noconfirm rlwrap

echo "Installing Babashka"
asdf_latest babashka

echo "Installing CLJ Kondo"
yay -S --noconfirm clj-kondo-bin

echo "Installing Rust"
asdf_latest rust

echo "Installing Dart"
asdf_latest dart

echo "Installing Flutter"
asdf_latest flutter

yay -S --noconfirm fzf

yay -S --noconfirm exa

yay -S --noconfirm tmux

echo "Installing Kubernetes stuff"
asdf_latest kubectl
asdf_latest kubectx
asdf_latest k3d
clear

yay -S --noconfirm aws-cli-v2-bin

yay -S --noconfirm gksu

echo "Installing Emacs"
yay -S --noconfirm emacs

git clone git@github.com:yuhribernardes/doom-emacs-config.git $HOME/.doom.d

rm -rf $HOME/.emacs.d
git clone --depth 1 https://github.com/doomemacs/doomemacs $HOME/.emacs.d
$HOME/.emacs.d/bin/doom install

echo "Installing Jetbrains IDEs"
sudo snap install intellij-idea-ultimate --classic
sudo snap install clion --classic
sudo snap install datagrip --classic
sudo snap install goland --classic
sudo snap install webstorm --classic
clear

yay -S --noconfirm insomnia-bin

yay -S --noconfirm httpie

yay -S --noconfirm docker

sudo systemctl enable --now docker.service
sudo systemctl enable --now containerd.service

sudo groupadd docker
sudo usermod -aG docker $USER

echo "Installing docker compose"

DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
mkdir -p $DOCKER_CONFIG/cli-plugins
curl -SL https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose

chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

yay -S --noconfirm flameshot

yay -S --noconfirm ulauncher-git
systemctl --user enable --now ulauncher.service

yay -S --noconfirm xclip

yay -S flatpak
flatpak install -y flathub com.obsproject.Studio

yay -S --noconfirm scrcpy

yay -S --noconfirm mesa xorg-server-devel

GO111MODULE=off go get github.com/unix-streamdeck/streamdeckd
GO111MODULE=off go get github.com/unix-streamdeck/streamdeckui
